# Permalinks
permalink:          pretty

# Setup
title:              cyber explained
tagline:            cyberexplained.github.io
url:                https://cyberexplained.github.io
paginate:           8

# Navigation
pages_list:
  Disclaimer:       '/disclaimer'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:         _sass
  style:            :compressed

# About/contact
author:
  name:             cyberexplained
  url:              https://cyberexplained.github.io
  email:            

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
